version: '3.5'


services:
  postgres:
    container_name: budgetBlocks
    image: postgres:latest
    environment:
      POSTGRES_USER: midex
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
       - postgres-db:/data/postgres
    ports:
      - "5432:5432"


volumes:
  postgres-db:
    driver: local